### ISSUE TITLE
questions on corpus encoding

### ISSUE THREAD

**Issue by sysu-zjw** [facebookresearch/multihop_dense_retrieval#6]
Hi, thanks for sharing the work. I didn't find the `scripts/get_embed.py` file as you mentioned in the readme file. I want to confirm that:
1) Is `scripts/encode_corpus.py` equivalent to `scripts/get_embed.py`?
2) Is `$MDR_HOME/data/hotpot_index/wiki_id2doc.json` used for `CORPUS_PATH`?

**Comment by xwhan** [comment]
Thank you for pointing out! Yes, the `get_embed.py` is renamed as `encode_corpus.py`. I have updated the readme. For `CORPUS_PATH`, you could easily build the input corpus file yourself, the `wiki_id2doc.json` should be the output of this step, instead of the input. I have also included a pointer to the HotpotQA corpus processing guide in the README to easily build the input corpus file.

**Comment by sysu-zjw** [comment]
Thanks for the reply @xwhan . 

Could you also share the input of `encode_corpus.py`? I am reproducing the raw corpus from Wikipedia dump according to `encode_datasets.py` functions, and so far had met several errors during encoding. I think it would be nice and more convenient if you could provide the processed input corpus.

**Comment by xwhan** [comment]
The processed corpus does have some empty passages. Either removing it or filling the "text" field with the document title should be fine. In `encode_datasets.py`, the RoBERTa encoder does not accept empty string for the 'text_pair' argument.
